#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Twist
from airsim_ros_pkgs.msg import CarControls
import sys, select, termios, tty

MAX_LIN_VEL = 1.0
MAX_ANG_VEL = 1.0

LIN_VEL_STEP_SIZE = 0.01
ANG_VEL_STEP_SIZE = 0.1

msg = """
Control the Airsim Car. 
---------------------------
Moving around:
        w
   a    s    d
        x

w/x : increase/decrease linear velocity ( ~ 1.0)
a/d : increase/decrease angular velocity ( ~ 1.0)

space key, s : force stop

CTRL-C to quit
"""

e = """
Communications Failed
"""

def getKey():
    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if rlist:
        key = sys.stdin.read(1)
    else:
        key = ''

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key

def vels(target_linear_vel, target_angular_vel):
    return "currently:\tlinear vel %s\t angular vel %s " % (target_linear_vel,target_angular_vel)

def makeSimpleProfile(output, input, slop):
    if input > output:
        output = min( input, output + slop )
    elif input < output:
        output = max( input, output - slop )
    else:
        output = input

    return output

def constrain(input, low, high):
    if input < low:
      input = low
    elif input > high:
      input = high
    else:
      input = input

    return input

def checkLinearLimitVelocity(vel):
    vel = constrain(vel, -MAX_LIN_VEL, MAX_LIN_VEL)
    return vel

def checkAngularLimitVelocity(vel):  
    vel = constrain(vel, -MAX_ANG_VEL, MAX_ANG_VEL)   
    return vel

status = 20
def converter_callback(message):
    global status, pub, car_commands
    print(message)    
    target_linear_vel   = message.linear.x
    target_angular_vel  = message.angular.z
    control_linear_vel  = 0.0
    control_angular_vel = 0.0

    target_linear_vel = checkLinearLimitVelocity(target_linear_vel)
    target_angular_vel = checkAngularLimitVelocity(target_angular_vel)
    print(vels(target_linear_vel, target_angular_vel))
    status = status + 1

    if status == 20 :
        print(message)
        status = 0
    
    #control_linear_vel = makeSimpleProfile(control_linear_vel, target_linear_vel, (LIN_VEL_STEP_SIZE/2.0))
    #control_angular_vel = makeSimpleProfile(control_angular_vel, target_angular_vel, (ANG_VEL_STEP_SIZE/2.0))
    control_linear_vel = target_linear_vel
    control_angular_vel = target_angular_vel

    if control_linear_vel==0.0:
        car_commands.handbrake = True
        car_commands.brake = 1
    elif control_linear_vel>0:
        car_commands.handbrake = False
        car_commands.brake = 0
        car_commands.manual = False
        car_commands.manual_gear = 0
        car_commands.throttle = control_linear_vel
        car_commands.steering = -control_angular_vel
    else:
        car_commands.handbrake = False
        car_commands.brake = 0
        car_commands.manual = True
        car_commands.manual_gear = -1
        car_commands.throttle = control_linear_vel
        car_commands.steering = -control_angular_vel

    print(car_commands)
    pub.publish(car_commands)

    

if __name__=="__main__":
    #settings = termios.tcgetattr(sys.stdin)
    car_commands = CarControls()
    car_commands.gear_immediate = True
    pub = rospy.Publisher('/airsim_node/Car_1/car_cmd', CarControls, queue_size=10)
    rospy.init_node('twist_2_car', anonymous=True)
    rospy.Subscriber('cmd_vel', Twist, converter_callback)
    rospy.spin()

    """
    pub = rospy.Publisher('car_cmd', CarControls, queue_size=10)

    status = 0
    target_linear_vel   = 0.0
    target_angular_vel  = 0.0
    control_linear_vel  = 0.0
    control_angular_vel = 0.0

    try:
        print(msg)
        while(1):
            key = getKey()
            if key == 'w' :
                target_linear_vel = checkLinearLimitVelocity(target_linear_vel + LIN_VEL_STEP_SIZE)
                status = status + 1
                print(vels(target_linear_vel,target_angular_vel))
            elif key == 'x' :
                target_linear_vel = checkLinearLimitVelocity(target_linear_vel - LIN_VEL_STEP_SIZE)
                status = status + 1
                print(vels(target_linear_vel,target_angular_vel))
            elif key == 'a' :
                target_angular_vel = checkAngularLimitVelocity(target_angular_vel + ANG_VEL_STEP_SIZE)
                status = status + 1
                print(vels(target_linear_vel,target_angular_vel))
            elif key == 'd' :
                target_angular_vel = checkAngularLimitVelocity(target_angular_vel - ANG_VEL_STEP_SIZE)
                status = status + 1
                print(vels(target_linear_vel,target_angular_vel))
            elif key == ' ' or key == 's' :
                target_linear_vel   = 0.0
                control_linear_vel  = 0.0
                target_angular_vel  = 0.0
                control_angular_vel = 0.0
                print(vels(target_linear_vel, target_angular_vel))
            else:
                if (key == '\x03'):
                    break

            if status == 20 :
                print(msg)
                status = 0

            # twist = Twist()
            # vel = VelCmd()
            car_commands = CarControls()
            car_commands.gear_immediate = True

            control_linear_vel = makeSimpleProfile(control_linear_vel, target_linear_vel, (LIN_VEL_STEP_SIZE/2.0))

            control_angular_vel = makeSimpleProfile(control_angular_vel, target_angular_vel, (ANG_VEL_STEP_SIZE/2.0))

            if control_linear_vel==0.0:
                car_commands.handbrake = True
                car_commands.brake = 1
            elif control_linear_vel>0:
                car_commands.handbrake = False
                car_commands.brake = 0
                car_commands.manual = False
                car_commands.manual_gear = 0
                car_commands.throttle = control_linear_vel
                car_commands.steering = -control_angular_vel
            else:
                car_commands.handbrake = False
                car_commands.brake = 0
                car_commands.manual = True
                car_commands.manual_gear = -1
                car_commands.throttle = control_linear_vel
                car_commands.steering = -control_angular_vel

            pub.publish(car_commands)

    except:
        print(e)

    finally:
        # twist = Twist()
        car_commands = CarControls()
        car_commands.handbrake = True
        car_commands.brake = 1
        pub.publish(car_commands)

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    """
